name: 书旗小说

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: shuqixiaoshuo
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【书旗小说】'
        run: |
          node shuqixiaoshuo.js
        env:
          lrb: ${{ secrets.lrb }}
          lrk: ${{ secrets.lrk }}
          splrb: ${{ secrets.splrb }}
          splrk: ${{ secrets.splrk }}
          wb: ${{ secrets.wb }}
          bb: ${{ secrets.bb }}
          rb: ${{ secrets.rb }}
          snb: ${{ secrets.snb }}
          rlb: ${{ secrets.rlb }}
          vlb: ${{ secrets.vlb }}
          llb: ${{ secrets.llb }}
          lru: ${{ secrets.lru }}
          lrbv: ${{ secrets.lrbv }}
          sb: ${{ secrets.sb }}
          btu: ${{ secrets.btu }}
          btb: ${{ secrets.btb }}
          spsnb: ${{ secrets.spsnb }}
          sprcu: ${{ secrets.sprcu }}
          sprcb: ${{ secrets.sprcb }}
          sp1v: ${{ secrets.sp1v }}
          sp2v: ${{ secrets.sp2v }}
          spsb: ${{ secrets.spsb }}
          liu: ${{ secrets.liu }}
          viu: ${{ secrets.viu }}
          spviu: ${{ secrets.spviu }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
