name: 中青阅读

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requests'
        run: pip install requests

      - name: 'run 中青阅读'
        # youth_read.py目录自己修改
        run: python3 youth.py
        # 目前最大5个账号，可按格式继续填写
        env:
            YOUTH_HEADER1: ${{ secrets.YOUTH_HEADER1 }}  #必须 账号1 body1
            YOUTH_READBODY1: ${{ secrets.YOUTH_READBODY1 }}  #必须 账号1 body1
            YOUTH_REDBODY1: ${{ secrets.YOUTH_REDBODY1 }}  #必须 账号1 body1
            YOUTH_READTIMEBODY1: ${{ secrets.YOUTH_READTIMEBODY1 }}  #必须 账号1 body1
            YOUTH_WITHDRAWBODY1: ${{ secrets.YOUTH_WITHDRAWBODY1 }}
            YOUTH_SHAREBODY1: ${{ secrets.YOUTH_SHAREBODY1 }}
            YOUTH_HEADER2: ${{ secrets.YOUTH_HEADER2 }}  #非必须 账号2 body1
            YOUTH_READBODY2: ${{ secrets.YOUTH_READBODY2 }}  #非必须 账号2 body1
            YOUTH_REDBODY2: ${{ secrets.YOUTH_REDBODY2 }}  #非必须 账号2 body1
            YOUTH_READTIMEBODY2: ${{ secrets.YOUTH_READTIMEBODY2 }}  #非必须 账号2 body1
            YOUTH_WITHDRAWBODY2: ${{ secrets.YOUTH_WITHDRAWBODY2 }}  #必须 账号1
            YOUTH_SHAREBODY2: ${{ secrets.YOUTH_SHAREBODY2 }}
            YOUTH_HEADER3: ${{ secrets.YOUTH_HEADER3 }}  #必须 账号1 body1
            YOUTH_READBODY3: ${{ secrets.YOUTH_READBODY3 }}  #必须 账号1 body1
            YOUTH_REDBODY3: ${{ secrets.YOUTH_REDBODY3 }}  #必须 账号1 body1
            YOUTH_READTIMEBODY3: ${{ secrets.YOUTH_READTIMEBODY3 }}  #必须 账号1 body1
            YOUTH_WITHDRAWBODY3: ${{ secrets.YOUTH_WITHDRAWBODY3 }}  #必须 账号1
            YOUTH_SHAREBODY3: ${{ secrets.YOUTH_SHAREBODY3 }}
            YOUTH_HEADER4: ${{ secrets.YOUTH_HEADER4 }}  #非必须 账号2 body1
            YOUTH_READBODY4: ${{ secrets.YOUTH_READBODY4 }}  #非必须 账号2 body1
            YOUTH_REDBODY4: ${{ secrets.YOUTH_REDBODY4 }}  #非必须 账号2 body1
            YOUTH_READTIMEBODY4: ${{ secrets.YOUTH_READTIMEBODY4 }}  #非必须 账号2 body1
            YOUTH_WITHDRAWBODY4: ${{ secrets.YOUTH_WITHDRAWBODY4 }}  #必须 账号1
            YOUTH_SHAREBODY4: ${{ secrets.YOUTH_SHAREBODY4 }}
            BARK: ${{ secrets.BARK }}  #非必须 bark通知
            SCKEY: ${{ secrets.SCKEY }}  #非必须 server酱通知
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}  #非必须 tg机器人token
            TG_USER_ID: ${{ secrets.TG_USER_ID }}  #非必须 tg机器人userId
            DD_BOT_ACCESS_TOKEN: ${{ secrets.DD_BOT_ACCESS_TOKEN }}  #非必须 钉钉机器人token
            DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}  #非必须 钉钉机器人secret
