name: 中青阅读body

on:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requests'
        run: pip install requests

      - name: 'run 中青阅读body'
        # youth_read.py目录自己修改
        run: python3 quanx/youtu_read.py
        env:
            YOUTH1_READ_BODY1: ${{ secrets.YOUTH1_READ_BODY1 }}  #必须 账号1 body1
            YOUTH1_READ_BODY2: ${{ secrets.YOUTH1_READ_BODY2 }}  #必须 账号1 body1
            YOUTH1_READ_BODY3: ${{ secrets.YOUTH1_READ_BODY3 }}  #必须 账号1 body1
            YOUTH1_READ_BODY4: ${{ secrets.YOUTH1_READ_BODY4 }}  #必须 账号1 body1
            YOUTH1_READ_BODY5: ${{ secrets.YOUTH1_READ_BODY5 }}  #必须 账号1 body1
            YOUTH2_READ_BODY1: ${{ secrets.YOUTH2_READ_BODY1 }}  #非必须 账号2 body1
            YOUTH2_READ_BODY2: ${{ secrets.YOUTH2_READ_BODY2 }}  #非必须 账号2 body1
            YOUTH2_READ_BODY3: ${{ secrets.YOUTH2_READ_BODY3 }}  #非必须 账号2 body1
            YOUTH2_READ_BODY4: ${{ secrets.YOUTH2_READ_BODY4 }}  #非必须 账号2 body1
            YOUTH2_READ_BODY5: ${{ secrets.YOUTH2_READ_BODY5 }}  #非必须 账号2 body1
